### DISCUSSION TITLE
How to run turso in CI (Github workflow)

### DISCUSSION THREAD

**Discussion by mattallty** [tursodatabase/turso-cli#453] [Q&A]
Hey,

is there an easy way to run `turso` (and `turso dev` specifically) within a Github workflow?
Install fails when doing:

```yml
- name: install turso
   run: curl -sSfL https://get.tur.so/install.sh | bash
   env:
     TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
```

btw, `TURSO_API_TOKEN` does not seem to be taken into account by the install script.
Also, `turso dev` asks for a sqld instance though the docs says it embeds its own instance.

The goal is to execute `turso` in my workflow to run tests. I guess a docker image would be the solution (running it as a [service container](https://docs.github.com/en/actions/using-containerized-services/about-service-containers)).

Happy to create an issue if needed

**Comment by CodingDoug** [comment]
The install script is independent of any invocations of the CLI itself, so setting the token in the environment for the install script wouldn't change the way those CLI invocations work. If you download and look at the script, you won't see any mentions of TURSO_API_TOKEN - it's just not used at all.

If you want to set the token for the CLI, you'd probably want to do that in every workflow step that actually runs the `turso` command after it's installed.

I just checked by running it myself, and `turso dev` doesn't require a token to be set at all (because it currently doesn't need to know anything about your managed database).  All it does by default is start a local sqld with a completely fresh in-memory database.  If you're having problems with that, it might help if you provide more complete and specific details about what you're doing that doesn't work.  I'm not clear what you mean by "`turso dev` asks for a sqld instance".  Do you have an actual error message, and the version of the CLI that printed it?  (`turso --version`)  The latest version right now is 0.62.1.

**Comment by kinthaiofficial** [comment]
Running Turso in CI works well once you sort out auth. Here's the pattern we use:

```yaml
# GitHub Actions
- name: Setup Turso CLI
  run: curl -sSfL https://get.tur.so/install.sh | bash
  
- name: Authenticate
  run: turso auth token --headless
  env:
    TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}

- name: Create ephemeral DB for tests
  run: |
    DB_NAME="ci-${{ github.run_id }}-${{ github.run_attempt }}"
    turso db create $DB_NAME --from-db ${{ env.BASE_DB }}
    echo "TEST_DB_URL=$(turso db show $DB_NAME --url)" >> $GITHUB_ENV
    echo "TEST_DB_TOKEN=$(turso db tokens create $DB_NAME)" >> $GITHUB_ENV

- name: Run tests
  run: npm test
  env:
    DATABASE_URL: ${{ env.TEST_DB_URL }}
    DATABASE_TOKEN: ${{ env.TEST_DB_TOKEN }}

- name: Cleanup
  if: always()
  run: turso db destroy ci-${{ github.run_id }}-${{ github.run_attempt }} --yes
```

The key insight: create a per-run ephemeral database branched from your test fixture DB, run tests against it, then destroy it. Parallel CI runs get isolated databases with no conflicts.

The `--from-db` flag makes this cheap — it's copy-on-write under the hood, not a full copy.

One gotcha: add `--yes` to the destroy step and use `if: always()` so cleanup runs even on test failures, otherwise you accumulate orphan databases.
